server:
  port: 8010
management:
  security:
    enabled: false
spring:
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: com.zf.*.*.entity
  type-enums-package: com.zf.*.*.enums
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    object-wrapper-factory: com.baomidou.mybatisplus.extension.MybatisMapWrapperFactory
    # sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

swagger:
  print-init: true
  enabled: true
  security-configuration:
    client-id: client-1
    client-secret: secretA
    scope-separator: \,
    use-basic-authentication-with-access-code-grant: true
  dockets:
    docket-api:
      base-package: com.zf.web
      group-name: api
      api-info:
        #   title:
        #  description:
        version: 2.0
        license: 2.0
      global-parameters:
        - name: token
          description: Access Token
          param-type: header
